# Site settings
title: 'Typosafe' # Your Title
tagline: "Where Scala code reveal its nature" # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
#baseurl: /blog # the subpath of your site, e.g. /blog/
